export interface GameMeta {
  slug: string
  title: string
  description: string
  icon: string
  category: 'reflexes' | 'precision' | 'memory' | 'perception' | 'typing' | 'arcade' | 'diction'
  unit: string
  higherIsBetter: boolean
  available: boolean
  /** Lien absolu (hors basePath /arena) vers un jeu statique externe de l'écosystème */
  external?: string
}

export const GAMES: GameMeta[] = [
  {
    slug: 'dungeon-elf-sound',
    title: 'Dungeon Elf',
    description: 'Action-RPG sonore — tranche les projectiles, trace des runes et personnalise la voix de tes sortilèges.',
    icon: '🧝',
    category: 'arcade',
    unit: 'niveau',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/dungeon-elf-sound/',
  },
  {
    slug: 'mg-airship',
    title: 'MG Airship',
    description: 'Pilote ton dirigeable et survive le plus longtemps possible.',
    icon: '🚢',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/MG_airship.html',
  },
  {
    slug: 'titan-rocket-run',
    title: 'Titan Rocket Run',
    description: 'Cours, saute depuis la rampe et va le plus loin possible.',
    icon: '🚀',
    category: 'arcade',
    unit: 'distance',
    higherIsBetter: true,
    available: true,
    external: '/titan-rocket-run/',
  },
  {
    slug: 'bzh-breach-storm',
    title: 'BZH Breach Storm',
    description: 'Roguelite de tir — explore des salles, bats des boss, collecte des fragments.',
    icon: '🌩️',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/bzh-breach-storm/',
  },
  {
    slug: 'spirit-overdrive',
    title: 'Spirit Overdrive',
    description: 'Course de garage en vue de dessus — dépasse tes adversaires.',
    icon: '🏎️',
    category: 'arcade',
    unit: 'position',
    higherIsBetter: false,
    available: true,
    external: '/arena/games/spirit-overdrive/',
  },
  {
    slug: 'bzh-nemeton-lockdown',
    title: 'BZH Nemeton Lockdown',
    description: 'Infiltration et énigmes dans un sanctuaire celtique sous haute surveillance.',
    icon: '🌿',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/bzh-nemeton-lockdown/',
  },
  {
    slug: 'lab-garden',
    title: 'Gold Garden Pro',
    description: 'Jardin de farming avec progression de graines, upgrades et dimensions cachées.',
    icon: '🌱',
    category: 'arcade',
    unit: 'or',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/lab-garden/',
  },
  {
    slug: 'lab-roguelite',
    title: 'Cyber Cellules v3',
    description: 'Roguelite cyberpunk — élimine des vagues d\'ennemis, récolte de l\'XP et affronte des boss.',
    icon: '🤖',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/lab-roguelite/',
  },
  {
    slug: 'magnet-maze',
    title: 'Magnet Maze',
    description: 'Coopération à deux écrans — guide l\'aimant pour révéler le fragment et ouvrir la sortie.',
    icon: '🧲',
    category: 'arcade',
    unit: 'labyrinthes',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/magnet-maze/',
  },
  {
    slug: 'escape-game-manager',
    title: 'Escape Game Manager',
    description: 'Gère un escape game en temps réel — groupes, salles, satisfaction et boutique.',
    icon: '🗝️',
    category: 'arcade',
    unit: 'argent',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/escape-game-manager/',
  },
  {
    slug: 'sniky',
    title: 'Sniky',
    description: 'Infiltration biopunk — évite les cônes de vision des drones, dash entre les patrouilles et vole les fragments.',
    icon: '🥷',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/sniky/',
  },
  {
    slug: 'tank-protocol',
    title: 'Tank Protocol',
    description: 'Survis aux vagues de drones ennemis — tir, dash et montée en puissance entre les rounds.',
    icon: '🛡️',
    category: 'arcade',
    unit: 'score',
    higherIsBetter: true,
    available: true,
    external: '/arena/games/tank-protocol/',
  },
  {
    slug: 'reaction',
    title: 'Reaction Time',
    description: 'Clique dès que le signal apparaît. Teste tes réflexes purs.',
    icon: '⚡',
    category: 'reflexes',
    unit: 'ms',
    higherIsBetter: false,
    available: true,
  },
  {
    slug: 'aim',
    title: 'Aim Trainer',
    description: 'Clique sur le maximum de cibles en 30 secondes.',
    icon: '🎯',
    category: 'precision',
    unit: 'hits',
    higherIsBetter: true,
    available: true,
  },
  {
    slug: 'typing',
    title: 'Typing Speed',
    description: 'Recopie le texte le plus vite possible. Score en WPM.',
    icon: '⌨️',
    category: 'typing',
    unit: 'WPM',
    higherIsBetter: true,
    available: true,
  },
  {
    slug: 'time-estimator',
    title: 'Time Estimator',
    description: 'Arrête le chrono quand tu penses que le temps demandé est écoulé.',
    icon: '⏱️',
    category: 'perception',
    unit: '% précision',
    higherIsBetter: true,
    available: true,
  },
  {
    slug: 'counter',
    title: 'Object Counter',
    description: 'Compte le nombre exact d\'objets affichés à l\'écran.',
    icon: '🔢',
    category: 'perception',
    unit: '% précision',
    higherIsBetter: true,
    available: true,
  },
  {
    slug: 'calembour',
    title: 'Calembour Vocal',
    description: 'Lis le virelangue à voix haute sans erreur. Le micro valide ta diction.',
    icon: '🗣️',
    category: 'diction',
    unit: 'phrases',
    higherIsBetter: true,
    available: true,
  },
  {
    slug: 'number-memory',
    title: 'Number Memory',
    description: 'Mémorise des séquences de chiffres de plus en plus longues.',
    icon: '🧠',
    category: 'memory',
    unit: 'niveau',
    higherIsBetter: true,
    available: false,
  },
  {
    slug: 'chiffer',
    title: 'Calcul Mental',
    description: 'Résous un maximum d\'opérations simples en 60 secondes.',
    icon: '🧮',
    category: 'memory',
    unit: 'bonnes réponses',
    higherIsBetter: true,
    available: false,
  },
]

export const CATEGORY_LABELS: Record<GameMeta['category'], string> = {
  reflexes: 'Réflexes',
  precision: 'Précision',
  memory: 'Mémoire',
  perception: 'Perception',
  typing: 'Frappe',
  arcade: 'Arcade',
  diction: 'Diction',
}
